on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        repository: kneip/dotnet-sonar
        tag_with_ref: true
        push: false
